### ISSUE TITLE
A question about channels

### ISSUE THREAD

**Issue by BrawnyJavier** [paladique/Talks#10]
It's it possible to make our own channels, like in my website?

**Comment by paladique** [comment]
Hi @Brawnyjavier,

Great question! The bot channel inspector, within the bot framework portal only allows you to use the channels provided. However, in my discoveries I have found the web chat channel to have a lot of possibilities on how to implement a bot on a site.  

Some references to check out:
https://docs.microsoft.com/en-us/bot-framework/portal-channel-inspector#the-channel-inspector

https://docs.botframework.com/en-us/channel-inspector/channels/WebChat/#navtitle

Hope that helps!
